### ISSUE TITLE
s3exists(NULL) returns TRUE

### ISSUE THREAD

**Issue by peterhurford** [robertzk/s3mpi#22]
```R
> s3mpi::s3exists(NULL)
[1] TRUE
```

(wat)

**Comment by robertzk** [comment]
Oops. Can you help fix?

On Wed, Apr 15, 2015 at 5:12 PM, Peter Hurford <notifications@github.com>
wrote:

> > s3mpi::s3exists(NULL)
> [1] TRUE
>
> (wat)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/s3mpi/issues/22>.
>



-- 
-Robert Krzyzanowski

**Comment by peterhurford** [comment]
https://github.com/robertzk/s3mpi/pull/23
